/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include "RingBuffer.h"
#include "RingBuffer_Test.h"
#if( RINGBUFFER_USECASE == RINGBUFFER_USECASE_INDEPENDENT )
#elif( RINGBUFFER_USECASE == RINGBUFFER_USECASE_MEMPOOL )
#include "MemPool.h"
#endif

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);

/*=======Test Reset Option=====*/
void resetTest(void);

void resetTest(void)
{
  tearDown();
  setUp();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/RingBuffer.c");
#if( RINGBUFFER_USECASE == RINGBUFFER_USECASE_INDEPENDENT )
  int8 * mempool = aligned_alloc(RINGBUFFER_SIZE, RINGBUFFER_SIZE);
  ringbuffer_start = mempool;
  printf("Address of mempool: %p\n", (void*)RINGBUFFER_STARTADDR);
  printf("Length of mempool: %p\n", (void*)RINGBUFFER_SIZE);
#elif( RINGBUFFER_USECASE == RINGBUFFER_USECASE_MEMPOOL )
  int8 * mempool = aligned_alloc(MEMPOOL_BLOCK_SIZE, MEMPOOL_SIZE);
  mempool_start = mempool;
  printf("Address of mempool: %p\n", (void*)MEMPOOL_STARTADDR);
  printf("Length of mempool: %p\n", (void*)(MEMPOOL_BLOCK_SIZE*MEMPOOL_MAX_NUM_BLOCKS));
#endif

  /* Tests for Create() */
  RUN_TEST(test_RingBuffer_Create_ReturnsOK, 54);
  RUN_TEST(test_RingBuffer_Create_AllocatedSpaceIsEmpty, 55);
  RUN_TEST(test_RingBuffer_Create_CorrectCapacityForElemSizeOne, 56);
  RUN_TEST(test_RingBuffer_Create_CorrectCapacityForElemSizeFour, 57);
  RUN_TEST(test_RingBuffer_Create_ZeroElemSizeShouldFail, 58);
  RUN_TEST(test_RingBuffer_Create_ThreeElemSizeShouldFail, 59);
  RUN_TEST(test_RingBuffer_Create_HugeElemSizeShouldFail, 60);

  /* Tests for Write */
  RUN_TEST(test_RingBuffer_Write_ReturnsOk, 63);
  RUN_TEST(test_RingBuffer_Write_ReturnsNotOk_WrongSize, 64);
  RUN_TEST(test_RingBuffer_Write_ReturnsNotOk_NullPointerToData, 65);
  RUN_TEST(test_RingBuffer_Write_ReturnsNotOk_NotEnoughSpace_Full, 66);

  /* Tests for Read*/
  RUN_TEST(test_RingBuffer_Read_ReturnsOk, 69);
  RUN_TEST(test_RingBuffer_Read_CorrectDataReturned, 70);
  RUN_TEST(test_RingBuffer_Read_ReturnsNotOk_SizeBiggerThanElement, 71);
  RUN_TEST(test_RingBuffer_Read_ReturnsNotOk_SizeSmallerThanElement, 72);
  RUN_TEST(test_RingBuffer_Read_ReturnsNotOk_NullPointerToData, 73);
  RUN_TEST(test_RingBuffer_Read_ReturnsNotOk_NoDataToRead, 74);

  /* Big Test */
  RUN_TEST(test_RingBuffer_ReadAndWriteLotsOfData, 77);
  RUN_TEST(test_RingBuffer_FillAndReadAndWriteAgain_OK, 78);
  RUN_TEST(test_RingBuffer_FillAndReadAndWriteAgain_CorrectData, 79);

  return (UnityEnd());
}
