/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include "RingBuffer.h"
#include "RingBuffer_Test.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);

/*=======Test Reset Option=====*/
void resetTest(void);

void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/ProtoBuf.c");

  uint8 * mempool = malloc(RINGBUFFER_MEMPOOL_SIZE);
  mempool_start = mempool;
  printf("Address of mempool: %p\n", (void*)RINGBUFFER_MEMPOOL_STARTADDR);
  printf("Length of mempool: %p\n", (void*)RINGBUFFER_MEMPOOL_SIZE);

  /* Tests for Create() */
  RUN_TEST(test_RingBuffer_Create_ReturnsOK, 54);
  RUN_TEST(test_RingBuffer_Create_AllocatedSpaceIsEmpty, 55);
  RUN_TEST(test_RingBuffer_Create_CorrectCapacityForElemSizeOne, 56);
  RUN_TEST(test_RingBuffer_Create_CorrectCapacityForElemSizeFour, 57);
  RUN_TEST(test_RingBuffer_Create_ZeroElemSizeShouldFail, 58);
  RUN_TEST(test_RingBuffer_Create_ThreeElemSizeShouldFail, 59);
  RUN_TEST(test_RingBuffer_Create_HugeElemSizeShouldFail, 60);



  return (UnityEnd());
}
